# Generated by Django 4.2.7 on 2026-10-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_testing", "0003_execution_async_state_and_logs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testexecution",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
    ]
