# Generated by Django 5.2.17 on 2026-10-05 09:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("api_testing", "0004_alter_testexecution_updated_at"),
        ("quality_gates", "0002_gaterun_gaterun_gate_run_idempotency"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PerformanceRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=128)),
                ("digest", models.CharField(max_length=64)),
                ("configuration_digest", models.CharField(max_length=64)),
                ("workload", models.JSONField()),
                ("task_id", models.CharField(max_length=36)),
                ("status", models.CharField(default="QUEUED", max_length=20)),
                ("summary", models.JSONField(default=dict)),
                ("error_code", models.CharField(blank=True, max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "environment",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api_testing.environment",
                    ),
                ),
                (
                    "gate",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_run",
                        to="quality_gates.gaterun",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api_testing.apiproject",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api_testing.apirequest",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "created_by", "idempotency_key"),
                        name="performance_run_idempotency",
                    )
                ],
            },
        ),
    ]
