# Generated by Django 4.2.7 on 2026-10-05 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api_testing", "0004_alter_testexecution_updated_at"),
        ("contracts", "0001_initial"),
        ("quality_gates", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GateRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=128)),
                ("request_digest", models.CharField(max_length=64)),
                ("plan", models.JSONField()),
                ("execution_ids", models.JSONField(default=list)),
                ("state", models.CharField(default="DISPATCHING", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "baseline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="baseline_runs",
                        to="contracts.contractversion",
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidate_runs",
                        to="contracts.contractversion",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api_testing.apiproject",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="gaterun",
            constraint=models.UniqueConstraint(
                fields=("project", "created_by", "idempotency_key"),
                name="gate_run_idempotency",
            ),
        ),
    ]
